### ISSUE TITLE
Elegir el tipo de tratamiento que hacer con los datos

### ISSUE THREAD

**Issue by migueorg** [Rastreador-medios-sociales/Scanner#3]
Tenemos que elegir el uso o estudio estadístico que daremos a los datos obtenidos

**Comment by agr8** [comment]
Yo trataría de utilizar **las ubicaciones** de las publicaciones de Instagram para, dada una ciudad, recopilar los sitios más comunes desde los que la gente sube fotos. Así, el usuario podría tener una lista de los lugares más visitados y/o frecuentados de la ciudad que desee.
